// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "datagrid1.h"

/////////////////////////////////////////////////////////////////////////////
// CDatagrid1

IMPLEMENT_DYNCREATE(CDatagrid1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CDatagrid1 properties

/////////////////////////////////////////////////////////////////////////////
// CDatagrid1 operations
